### PR TITLE
Add check for presence of @author javadoc tag

### PR DESCRIPTION
**Pull request by bgoodies**

### CODE REVIEW

**Comment by mjball** [comment]
:heart:

**Comment by jhaber** [comment]
I force-pushed to master and it seems like it messed up this PR, but I added the feature [here](5b3bab409b3d14a4af08de5daacb3546b042fa79)

**Comment by bgoodies** [comment]
thanks. my bad. i didn't notice the commit weirdness.

**Comment by jhaber** [comment]
The PR looked fine when you sent it but I took some upstream changes and did a force push and it got messed up

**Pull request closed without merging**
